apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-15-awx-postgres-15-0
  namespace: automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: azurefile-postgres-fix
  resources:
    requests:
      storage: 2Gi
